[project]
name = "anthropic-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=0.3.25",
    "pandas>=2.3.0",
    "pydantic>=2.11.7",
]
